src/components/codeGeneration/index.ts
i think i got this from the docs lol
=> chore: remove needless code

public/extracredit.json, src/components/pages/ExtraCreditPage.tsx, src/components/pages/OverviewPage.tsx
fix links to open to new tab (view readme, extra credit)
=> change links to open to new tab

public/vanillareforged.json
This will probably be my only contribution if this gets merged as I don't know how to code in TypeScript
=> Consumables in Vanilla Reforged

src/components/pages/JokersPage.tsx
instead of counting up to 15 and stopping there
=> fix: dynamically load placeholder jokers

src/components/codeGeneration/Jokers/index.ts, src/components/generic/validationUtils.ts
Added invalid character sanitization and commented out some checks regarding it (they are not needed because it all gets escaped either way)
From my tests it all works fine but i didn't try to find an edge case super hard
=> Joker description sanitization

src/components/codeGeneration/Jokers/effectUtils.ts, src/components/codeGeneration/Jokers/effects/ModifyBlindRequirementEffect.ts, src/components/codeGeneration/Jokers/effects/SetAnteEffect.ts, src/components/data/Jokers/Effects.ts
=> Added #183, Fixed Set ante effect not working correctly

src/App.tsx, src/components/ConsumableCard.tsx, src/components/JokerCard.tsx
i have deleted many jokers on accident
=> feat: add deletion confirmation to jokers and consumables

src/components/EditConsumableInfo.tsx, src/components/EditJokerInfo.tsx
=> chore: change touchstart to touchend

src/components/EditConsumableInfo.tsx, src/components/EditJokerInfo.tsx
=> revert changes

README.md, src/components/codeGeneration/Jokers/conditionUtils.ts, src/components/codeGeneration/Jokers/conditions/CumulativeChipsCondition.ts, src/components/data/Jokers/Conditions.ts, src/components/ruleBuilder/Inspector.tsx
works on my machine 👍
also changed the negate condition icon because people were thinking it was a delete button
=> feat: add cumulative chips condition

public/vanillareforged.json, src/components/codeGeneration/Jokers/conditions/CardIndexCondition.ts, src/components/codeGeneration/Jokers/conditions/RankCardCondition.ts, src/components/codeGeneration/Jokers/conditions/SuitCardCondition.ts, src/components/codeGeneration/Jokers/index.ts, src/components/data/Jokers/Conditions.ts
List of issues:
- https://github.com/Jayd-H/joker-forge/issues/236
- https://github.com/Jayd-H/joker-forge/issues/245
- https://github.com/Jayd-H/joker-forge/issues/247
- https://github.com/Jayd-H/joker-forge/issues/215
=> Bunch of bug fixes

src/components/codeGeneration/Jokers/conditions/JokerCountCondition.ts, src/components/data/BalatroUtils.ts
not sure if this is elegant, but it works
fixes #253
=> fix: allow custom rarities in jokerCount condition

src/components/Sidebar.tsx
=> discord link

src/components/codeGeneration/Jokers/conditions/BlindRequirementsCondition.ts, src/components/codeGeneration/Jokers/conditions/ProbabilityIdentifierCondition.ts, src/components/codeGeneration/Jokers/effectUtils.ts, src/components/codeGeneration/Jokers/effects/CombineRanksEffect.ts, src/components/codeGeneration/Jokers/index.ts, src/components/codeGeneration/entry.ts, src/components/data/Jokers/Conditions.ts, src/components/data/Jokers/GameVars.ts
- https://github.com/Jayd-H/joker-forge/issues/223
=> issue #223 and some bug fixes

README.md, src/components/codeGeneration/Jokers/effects/DisableBossBlindEffect.ts, src/components/data/Jokers/Effects.ts
=> feat: add passive trigger to disableBossBlind effect

src/components/codeGeneration/Jokers/effects/LevelUpHandEffect.ts
=> fix: allow multiple levelUpHand effects in a row

src/components/codeGeneration/Jokers/effects/ConsideredAsEffect.ts, src/components/codeGeneration/Jokers/effects/CopyJokerAbilityEffect.ts, src/components/codeGeneration/Jokers/effects/DisableBossBlindEffect.ts, src/components/codeGeneration/Jokers/effects/SplashEffect.ts, src/components/codeGeneration/Jokers/index.ts
issue #311 should be fixed now
=> fix: passive trigger overrides normal triggers

public/vanillareforged.json, src/components/codeGeneration/Jokers/conditionUtils.ts, src/components/codeGeneration/Jokers/conditions/JokerPositionCondition.ts, src/components/codeGeneration/Jokers/conditions/JokerRarityCondition.ts, src/components/codeGeneration/Jokers/conditions/JokerStickerCondition.ts, src/components/codeGeneration/Jokers/triggerUtils.ts, src/components/data/Jokers/Conditions.ts, src/components/data/Jokers/Effects.ts, src/components/data/Jokers/Triggers.ts
also added this joker index/sticker condition and updated baseball card
trigger name may need to be changed if it generates confusion 👍
=> feat: add joker_evaluated trigger

src/components/codeGeneration/Card/effects/CopyJokerEffect.ts, src/components/codeGeneration/Card/effects/CreateJokerEffect.ts, src/components/codeGeneration/Card/effects/DestroyJokerEffect.ts, src/components/codeGeneration/Consumables/effects/CreateJokerEffect.ts, src/components/codeGeneration/Jokers/conditionUtils.ts, src/components/codeGeneration/Jokers/conditions/JokerKeyCondition.ts, src/components/codeGeneration/Jokers/effects/CopyJokerEffect.ts, src/components/codeGeneration/Jokers/effects/CreateJokerEffect.ts, src/components/codeGeneration/Jokers/effects/DestroyJokerEffect.ts, src/components/data/Jokers/Conditions.ts, src/components/data/Jokers/Effects.ts
also automatically adds j_ to joker_key field
=> feat: add joker_key condition to joker_evaluated trigger

src/components/codeGeneration/Jokers/conditionUtils.ts, src/components/codeGeneration/Jokers/conditions/CheckFlagCondition.ts, src/components/codeGeneration/Jokers/effectUtils.ts, src/components/codeGeneration/Jokers/effects/EmitFlagEffect.ts, src/components/data/Jokers/Conditions.ts, src/components/data/Jokers/Effects.ts
we can also use flags in the future for shop appeareance conditions
=> feat: add emit flag effect and check flag condition

src/components/JSONImportExport.ts, src/components/pages/JokersPage.tsx
=> fix: make the defaults for card appearance true

src/components/JSONImportExport.ts, src/components/codeGeneration/Consumables/conditions/AnteLevelCondition.ts, src/components/codeGeneration/Consumables/conditions/RemainingHandsCondition.ts, src/components/data/Jokers/Effects.ts, src/components/pages/ConsumablesPage.tsx, src/components/ruleBuilder/Inspector.tsx
also changed some `||` to `??` across some conditions and on normalizeJokerData
=> feat: add more triggers to modify blind requirement effect

src/components/codeGeneration/Jokers/effects/LevelUpHandEffect.ts
=> fix: allow any triggers when leveling up current hand

src/components/codeGeneration/Card/conditionUtils.ts, src/components/codeGeneration/Card/conditions/CheckFlagCondition.ts, src/components/codeGeneration/Card/effectUtils.ts, src/components/codeGeneration/Card/effects/EmitFlagEffect.ts, src/components/codeGeneration/Consumables/conditionUtils.ts, src/components/codeGeneration/Consumables/conditions/CheckFlagCondition.ts, src/components/codeGeneration/Consumables/effectUtils.ts, src/components/codeGeneration/Consumables/effects/EmitFlagEffect.ts, src/components/data/Card/Conditions.ts, src/components/data/Card/Effects.ts, src/components/data/Consumables/Conditions.ts, src/components/data/Consumables/Effects.ts, src/components/ruleBuilder/RuleBuilder.tsx
forgor i had the pr open, also added grid snapping 👍
implements #316
=> feat: add flags to consumables/cards & add grid snapping

src/App.tsx, src/components/JSONImportExport.ts, src/components/Sidebar.tsx, src/components/codeGeneration/Card/effectUtils.ts, src/components/codeGeneration/Card/effects/PlaySoundEffect.ts, src/components/codeGeneration/Consumables/effectUtils.ts, src/components/codeGeneration/Consumables/effects/PlaySoundEffect.ts, src/components/codeGeneration/Jokers/effectUtils.ts, src/components/codeGeneration/Jokers/effects/PlaySoundEffect.ts, src/components/codeGeneration/Jokers/effects/SavedEffect.ts, src/components/codeGeneration/entry.ts, src/components/data/BalatroUtils.ts, src/components/data/Card/Effects.ts, src/components/data/Consumables/Effects.ts, src/components/data/Jokers/Effects.ts, src/components/pages/SoundPage.tsx
<h2> Note: the audio replay i plan on changing later or letting someone else do it, just didn't have enough time today and dont want to leave this sitting still</h2>
<h3>Some other code related screenshots</h3>
=> feat: Sounds

src/App.tsx, src/components/JSONImportExport.ts, src/components/codeGeneration/Consumables/effects/CreateConsumableEffect.ts, src/components/codeGeneration/Jokers/effects/CreateConsumableEffect.ts, src/components/codeGeneration/Jokers/effects/DestroySelfEffect.ts, src/components/codeGeneration/Jokers/effects/EmitFlagEffect.ts, src/components/data/Consumables/Effects.ts, src/components/data/Jokers/Effects.ts, src/components/generic/validationUtils.ts, src/components/pages/SoundPage.tsx, src/components/ruleBuilder/Inspector.tsx, src/components/ruleBuilder/RuleBuilder.tsx
- Fixed parameter edits not saving inside of loops
- Fixed showing false error messages in card descriptions
- Fixed generic compare only taking gamevars into value2
- Fixed sounds accepting file formats other than .ogg (also added a small caption to the user)
- Fixed sound files not importing correctly from save files
- (Feat) Added parameters for EmitFlag and DestroySelf to disable custom message. Also added a new parameter to DestroySelf to customise the destroy animation
- (Feat) Added soulable parameter for create consumable effect (determines whether or not soul cards/black hole can spawn)
- (Feat) Added more parameters to CreateConsumable (consumable effect), and also reworked its code function structure to be easier to follow
=> Many issues and bug fixes; Parameter additions

src/components/Sidebar.tsx
chore: i feel bad about accepting donations for myself when this project has evolved more into a group thing
=> chore: i feel bad about accepting donations for myself when this project has evolved more into a group thing
